### ISSUE TITLE
Fix finding spec directory

### ISSUE THREAD

**Issue by ExceLLent404** [sporto/rails-go-to-spec-vscode#10]
Hi! I found your extension and find it useful. But I encountered a problem while using it.

I use Docker to develop Rails applications. In this case, it is common to have the root directory with of all Rails application files named as `/app` or `/usr/src/app`. For this reason, when I try to jump from any file in the `app` directory to the corresponding `spec`, the extension [tries to switch](https://github.com/sporto/rails-go-to-spec-vscode/blob/fa9cc0cba3d3967b5c311f7e845d46c8a01855f7/src/resolver.ts#L32) between these folders and prompts me to create a file

`/usr/src/spec/app/models/some_model_spec.rb`

instead of opening the existing and correct

`/usr/src/app/spec/models/some_model_spec.rb`

It would be nice if you fix this behavior.

It might be worth to add a setting option to specify the root directory and ignore it

**Comment by sporto** [comment]
I don't quite understand why you would expect to go to `/usr/src/app/spec/models/some_model_spec.rb`
I expect to jump to `/usr/src/spec/models/some_model_spec.rb` in this case.
What is the root of your rails app?

**Comment by sporto** [comment]
Here is a relevant test https://github.com/sporto/rails-go-to-spec-vscode/blob/master/src/test/suite/extension.test.ts#L123

**Comment by sporto** [comment]
I assume the project root is in `/usr/src/app/` in your case. So the a model will be in `/usr/src/app/app/models/user.rb` correct? The double `app` here does fool the resolver.

**Comment by sporto** [comment]
Do you think this is what you need? https://github.com/sporto/rails-go-to-spec-vscode/pull/11

**Comment by ExceLLent404** [comment]
Yes, that's right - `/usr/src/app/` is the root and contains `app` and `spec` directories and other files inside it.

I copied your changes into the extension source code and now it works correct. Thanks!

I think that's enough. Although there may be situations where `app` occurs twice for another reason. For example, if someone is using Windows, stores their Rails project on Desktop and its username is "app" ¯\\_(ツ)_/¯. Then the path to some model will be `C:\Users\app\Desktop\Rails\app\models\user.rb`.

This is probably overthinking

**Comment by sporto** [comment]
Published 1.2
