### ISSUE TITLE
Jump from controller to request spec if no controller spec found

### ISSUE THREAD

**Issue by hubertjakubiak** [sporto/rails-go-to-spec-vscode#4]
> Controller specs can be used to describe the behaviour of Rails controllers. As of version 3.5, however, controller specs are discouraged in favour of request specs (which also focus largely on controllers, but capture other critical aspects of application behaviour as well). Controller specs will continue to be supported until at least version 4.0 (see the [release notes](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#rails-support-for-rails-5) for details).

WDYT about such new feature?

**Comment by evanlouden** [comment]
Or now jump to system spec as request specs have been replaced by system specs?

**Comment by sporto** [comment]
I have published a new version of the extension that should address this.
The extension is now sporto2.rails-go-to-spec-2
I wasn't able to recover my previous publisher name or extension name.

**Comment by monkseal** [comment]
@sporto Thank you for updating this!
