### ISSUE TITLE
Wrong guessing for spec file ?

### ISSUE THREAD

**Issue by thomasdarde** [sporto/rails-go-to-spec-vscode#7]
Great extension !

When using it from this file:
`aproject/app/lib/internal/result.rb`

it opens
`aproject/app/spec/lib/internal/result_spec.rb`

instead of 
`aproject/spec/app/lib/internal/result_spec.rb`

**Comment by sporto** [comment]
I have published a new version of the extension that I believe fixes this.

However given
`aproject/app/lib/internal/result.rb`

it will jump to
`aproject/spec/lib/internal/result_spec.rb`

The extension is now `sporto2.rails-go-to-spec-2`
I wasn't able to recover my previous publisher name or extension name.

**Comment by thomasdarde** [comment]
Hi @sporto 
I see the new extensions and the changes to create it in the recent commits.
But not the changes to open the correct file ?

`aproject/app/lib/sg_stripe/customer.rb`
opens 
`aproject/app/spec/lib/sg_stripe/customer.rb`

instead of 
`aproject/spec/lib/sg_stripe/customer.rb`
or
`aproject/spec/app/lib/sg_stripe/customer.rb`

I did check that the old extensions was removed and vs restarted

**Comment by sporto** [comment]
I checked on our code base and what I noticed is that the lib dir is not in `app`
e.g. `aproject/lib/billing/http_client.rb`
This project is a several years old. And was generated with an older version of Rails.
Has Rails changed where the `lib` dir goes?

**Comment by sporto** [comment]
I guess we need to support having `lib` in `/lib` and `/app/lib`

**Comment by sporto** [comment]
@thomasdarde
Published new version, please test it

**Comment by thomasdarde** [comment]
Hi @sporto 
This is great ! Thank you very much.

Seeing the issue I have a question , what's under `app/lib` is reloaded at each request , what's under `lib/` is only reloaded at rails restart. This is why we have both of them

Maybe we should have `app/lib/test.rb` routed to `spec/app/lib/test_spec.rb` ?
Or you're solution is nice because we can't have `app/lib/test.rb` and `lib/test.rb` in the same project

**Comment by sporto** [comment]
@thomasdarde I believe is confusing to have something like `lib/something.rb` and `app/lib/something.rb` in the same project. So I rather discourage that. So for the moment I will keep it as is.
