### ISSUE TITLE
Add command to context menu for ruby files

### ISSUE THREAD

**Issue by lstrzebinczyk** [sporto/rails-go-to-spec-vscode#8]
Hey: )

I was wondering if it is possible to push the feature into context menu on `.rb` files. What do you think?

**Comment by sporto** [comment]
I would be happy to take a PR to do this.

**Comment by lstrzebinczyk** [comment]
I will try : )

**Comment by lstrzebinczyk** [comment]
Implemented in https://github.com/sporto/rails-go-to-spec-vscode/pull/9
